# Control your input devices
# See https://wiki.hypr.land/Configuring/Variables/#input

input {
  kb_layout  = us
  kb_options = compose:caps  # ,grp:alt_space_toggle to add layout switching

  # Keyboard repeat speed
  repeat_rate  = 40
  repeat_delay = 600

  # Increase sensitivity for mouse/trackpad (default: 0)
  # sensitivity = 0.35

  touchpad {
    natural_scroll = true   # Use natural (inverse) scrolling

    # Use two-finger clicks for right-click instead of lower-right corner
    # clickfinger_behavior = true

    scroll_factor = 0.3     # Control the speed of scrolling
  }
}

# Touchpad gesture: 3-finger horizontal swipe to change workspaces
gesture = 3, horizontal, workspace

# Scroll faster in the terminal
windowrule = match:class foot, scroll_touchpad 1
