# Change the default Omarchy look'n'feel

# https://wiki.hyprland.org/Configuring/Variables/#general
general {
  gaps_in  = 0  # No gaps between windows
  gaps_out = 0

  # layout = master  # Use master layout instead of dwindle
}

# https://wiki.hyprland.org/Configuring/Variables/#decoration
decoration {
  rounding = 0  # Square window corners

  shadow {
    enabled = true
  }

  blur {
    enabled = true
  }
}

animations {
  enabled = true
}
