# ============================================
# HYPRLAND WINDOW RULES CONFIGURATION
# Matches are strictly Regex and must fully match.
# See https://wiki.hypr.land/Configuring/Window-Rules/
# ============================================

# Run 'hyprctl clients | grep -i youtube' to find the 'class:' and 'title:' for window rules

# disable transparency on all window

#windowrule = opacity 1.0, match:class .*

# ============================================
# WORKSPACE ASSIGNMENTS
# ============================================

# WhatsApp - Always on workspace 3
# Matches title "WhatsApp" or class containing "whatsapp"
# windowrule = workspace 3, match:title ^(WhatsApp)$
# windowrule = workspace 3, match:class .*whatsapp.*

# Discord - Always on workspace 4
#windowrule = workspace 4, match:class ^(vesktop|discord)$
#windowrule = workspace 4, match:title ^(Discord)$

# Spotify & Music - Always on workspace 5
#windowrule = workspace 5, match:class ^(Spotify|spotify)$
#windowrule = workspace 5, match:title ^(Spotify|YouTube Music)$
#windowrule = workspace 5, match:class ^(brave-music\.youtube\.com__-Default)$


windowrule = float 1, match:class ^(brave-google\.com__-Default)$
windowrule = size 1100 700, match:class ^(brave-google\.com__-Default)$
windowrule = center 1, match:class ^(brave-google\.com__-Default)$

# floating pop ups

windowrule = float 1, match:class ^(DesktopEditors|xdg-desktop-portal-gtk|Xdg-desktop-portal-gtk)$

windowrule = center 1, match:class ^(DesktopEditors|xdg-desktop-portal-gtk|Xdg-desktop-portal-gtk)$

windowrule = size 60% 50%, match:class ^(DesktopEditors|xdg-desktop-portal-gtk|Xdg-desktop-portal-gtk)$


# ============================================
# FLOATING WINDOWS
# ============================================

# Custom Floating Class
windowrule = float 1, size 60% 50%, center 1, match:class ^(floating)$
